### ISSUE TITLE
Not possible to add pdf file to a group library

### ISSUE THREAD

**Issue by ghost** [ZotPlus/zotero-link-local-files#1]
Hello,
Every time I tried to add a pdf file into a group library (that I own), I couldn't, and received this error : "Transaction in progress in Zotero.Sync.Server._checkSyncUser". It was possible to add any kind of other file, but no pdf.
I've tried to disable all my extensions, and everything worked smooth. So, I enabled one extension after the other to find the culprit one. This extension was the origin of the problem : zotero-link-local-files . I had the exact same problem with Zotero standalone and when I disabled this extension, it's working again.

Thks in advance

**Comment by retorquere** [comment]
Sorry I overlooked this for so long. I'll have a look at it.

**Comment by retorquere** [comment]
What version are you on?

**Comment by ghost** [comment]
Sorry, I do not use Zotero-link-local-files extension anymore and I can't remember which version was installed as this error occured. Thanks anyway
