### ISSUE TITLE
.xpi file link broken on zotplus website

### ISSUE THREAD

**Issue by janmattijs** [ZotPlus/zotero-link-local-files#2]
The link to the XPI provided on the https://zotplus.github.io/link-local-files/index.html page is broken. 
https://github.com/ZotPlus/zotero-link-local-files/releases/download/0.0.9/zotero-link-local-files-0.0.9.xpi leads to a 404. 

I don't know how to use the other formats (Zip or tar) that seem to create folders. I hope this version will work on Firefox 43 that disabled the "unsigned" previous version!

**Comment by retorquere** [comment]
I'm trying to fix it, but the mozilla infrastructure is horribly broken right now, and I can't release anything.

**Comment by reyman** [comment]
Any news about xpi ? Link is broken, but i see that version is equal to 0.12. I'm really interested for desktop version :)

**Comment by retorquere** [comment]
Apologies for the delay (and good on you to remind me). I think things are fixed now -- as far as I can tell, the update should happen automatically, but if not, you can find the latest release [here](https://github.com/ZotPlus/zotero-link-local-files/releases/latest).

**Comment by reyman** [comment]
thanks :)

2016-01-27 11:55 GMT+01:00 retorquere notifications@github.com:

> Apologies for the delay (and good on you to remind me). I think things are
> fixed now -- as far as I can tell, the update should happen automatically,
> but if not, you can find the latest release here
> https://github.com/ZotPlus/zotero-link-local-files/releases/latest.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ZotPlus/zotero-link-local-files/issues/2#issuecomment-175555663
> .

## 

http://stackoverflow.com/users/385881/reyman64

**Comment by retorquere** [comment]
If you have seen it work, could you close the issue? I'd rather not close the issue until I know I've solved the problem.

**Comment by janmattijs** [comment]
Works. I had to update manually, possibly because I was still with version 0.0.7 :)
Closing issue. Thanks!
