### ISSUE TITLE
Import bbitex with relative link don't work with zotfile 4.1.6  and zotero 4.0.28 ? 

### ISSUE THREAD

**Issue by reyman** [ZotPlus/zotero-link-local-files#3]
Hi,

So, i try the latest version, with Zotfile 4.1.6 and Zotero 4.0.28.

I have a .bib with file like this 

```
@book{Fogel2006b,
author = {Fogel, David B.},
editor = {Fogel, David B.},
file = {:/home/reyman/Bureau/tempzotero/Fogel_2006_Evolutionary Computation Toward a New Philosophy of Machine Intelligence, 3rd Edition.pdf:application/pdf},
isbn = {978-0-471-66951-7},
keywords = {PHD},
mendeley-tags = {PHD},
pages = {296},
publisher = {Wiley},
title = {{Evolutionary Computation: Toward a New Philosophy of Machine Intelligence, 3rd Edition}},
url = {http://eu.wiley.com/WileyCDA/WileyTitle/productCd-0471669512.html},
year = {2006}
}
```

The folder exist with the correct file : 

![selection_012](https://cloud.githubusercontent.com/assets/466329/12612897/4f59454c-c4f6-11e5-9946-bf119215b8c5.png)

I use this Zotfile configuration : 

![selection_010](https://cloud.githubusercontent.com/assets/466329/12612886/36fafd9c-c4f6-11e5-93ee-4c67ec828acb.png)

When i try to import this bib, the file continue to be copied by zotero in `.zotero` storage folder :/

I try to reinstall extensions, restart multiple time, without succes :/

**Comment by reyman** [comment]
Any idea ? :/

**Comment by retorquere** [comment]
The extension doesn't pick up the path from zotfile, only the path specified in [Linked Attachment Base Directory](https://www.zotero.org/support/preferences/advanced).

**Comment by reyman** [comment]
Ok i remove zotfile and retry with "Linked Attachment Base Directory", i give you some news at the end of day

**Comment by reyman** [comment]
Ok, i remove zotfile, and try to use your extension using the "linked base directory" path :+1: 

![selection_013](https://cloud.githubusercontent.com/assets/466329/13004348/4ba6cbd6-d17b-11e5-8f53-a64bedc4bb74.png)

As see in the image posted previously, the pdf linked in bibtex already exist in this folder.

But, Zotero continue to recopy the pdf file in Zotero specific folder during bibtex importation. Perhaps a bug ?

**Comment by retorquere** [comment]
verified as a bug

**Comment by retorquere** [comment]
.19 fixes it for me.

**Comment by reyman** [comment]
Great news :) Thanks

2016-02-13 19:37 GMT+01:00 retorquere notifications@github.com:

> .19 fixes it for me.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ZotPlus/zotero-link-local-files/issues/3#issuecomment-183719314
> .

## 

http://stackoverflow.com/users/385881/reyman64
