### ISSUE TITLE
Zotero 5 compatibility

### ISSUE THREAD

**Issue by marcomorotti** [ZotPlus/zotero-link-local-files#4]
When I try to install from : Extensions; Install Add On from File; I have the error: the add on is incompatible with this version.
Thanks a lot
Marco

**Comment by retorquere** [comment]
There is not yet a version that is compatible with Zotero 5.

**Comment by Zythyr** [comment]
+1 for Zotero 5 support.

**Comment by peeter-t2** [comment]
+1 Great add on I used also some years ago, now there seems to be no good alternative to it. Will appreciate an update, thanks!
Note Zotero 4 will stop being able to sync starting from August 18, 2018, so this may be another reason. Thanks for app in any case, it's been very useful!

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 0.6.61.emile.Emilianos-MacBook-Air.local](https://github.com/retorquere/zotero-link-local-files/releases/download/builds/zotero-link-local-files-0.6.61.emile.Emilianos-MacBook-Air.local.xpi) (undefined).

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.0.emile.Emilianos-MacBook-Air.local](https://github.com/retorquere/zotero-link-local-files/releases/download/builds/zotero-link-local-files-5.0.0.emile.Emilianos-MacBook-Air.local.xpi) (undefined).

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.0.emile.Emilianos-MacBook-Air.local](https://github.com/retorquere/zotero-link-local-files/releases/download/builds/zotero-link-local-files-5.0.0.emile.Emilianos-MacBook-Air.local.xpi) (undefined).

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.0.13](https://github.com/retorquere/zotero-link-local-files/releases/download/builds/zotero-link-local-files-5.0.0.13.xpi) ("what now circle?!").

**Comment by retorquere** [comment]
5.0.0.13 should work, but is untested; I don't have my dev system at hand for another week.

**Comment by peeter-t2** [comment]
Can confirm that it worked on my Zotero 5.0.54 with no noticeable problems. Thanks a lot for quick reaction!!

**Comment by retorquere** [comment]
Thanks for the confirmation, I've scheduled 5.0.1 for release.
