### ISSUE TITLE
This plugin doesn't work if Linked Attachements Base Directory is not configured

### ISSUE THREAD

**Issue by 01baftb** [ZotPlus/zotero-link-local-files#6]
The recent release of this plugin, v5.0.1, doesn't work unless user has configured `Linked Attachments Base Directory` which is located under `Edit >> Preferences >> Advanced >> Files and Folders`.

The requirement of having  `Linked Attachments Base Directory` configured creates two issues: 

1) What if a user does NOT want to configure this value? 

2) If the user has  `Linked Attachments Base Directory` configured and then drags a PDF file from outside of the configured directory, user gets a `File not found` error after metadata retrieval is completed. The only work around for this error is to disable the zotero-link-local-files plugin when dragging PDF files outside of the base directory. 

I think the proposed solution is to allow absolute path and not force the users to have `Linked Attachments Base Directory` configured.

**Comment by retorquere** [comment]
The readme does say that it only works for attachments in the base directory and that this needs to be configured. I'll try to further emphasize this in the readme, but that behavior is unlikely to change. Linked files in the base directory are safe to sync; outside the base directory linked files are likely to only work on the system where the file was attached.

1. If the user does not want configure this value, this plugin won't do anything for the reason outlined above.
2. For this I'd need to see the debug log. Please go to `Help` - `Debug Output Logging` - `Restart with logging enabled`, let Zotero restart, replay the scenario, and then attach the debug log (`Help` - `Debug Output Logging` - `View Output`) here.

**Comment by 01baftb** [comment]
@retorquere I wasn't able to reproduce the issue today. You can close issue. If it happens again and if I figure out a way to reproduce, I will report back with a debug logging output also.
