### ISSUE TITLE
libraryID=undefined

### ISSUE THREAD

**Issue by vancleve** [ZotPlus/zotero-link-local-files#7]
Linking isn't working for me because

`libraryID=undefined`

when I interrogate it and thus

https://github.com/retorquere/zotero-link-local-files/blob/37561dea5f23784afaad3f02907a5983bf247597/content/LinkLocalFiles.ts#L28

falis.

Any thoughts?

**Comment by retorquere** [comment]
:robot: this is your friendly neighborhood build bot announcing [test build 5.0.1.19](https://github.com/retorquere/zotero-link-local-files/releases/download/builds/zotero-link-local-files-5.0.1.19.xpi) ("fixes #7")

Install in Zotero by downloading [test build 5.0.1.19](https://github.com/retorquere/zotero-link-local-files/releases/download/builds/zotero-link-local-files-5.0.1.19.xpi), opening the Zotero "Tools" menu, selecting "Add-ons", open the gear menu in the top right, and select "Install Add-on From File...".

**Comment by retorquere** [comment]
can you try 5.0.1.19 linked to above?

**Comment by vancleve** [comment]
yup, it works, thanks!

unrelated, when debugging these zotero packages, I know how to uznip the .xpi and load run zotero from the source files, but how would I do the same with your package (i.e., edit the .ts file and then prepare the package)?

**Comment by retorquere** [comment]
The package is prepared by running `npm run build`; the build results will be in the directory `build` and a zipped version is put in the directory `xpi`. You can directly run from the `build` directory.
